# Generated by Django 5.2.5 on 2025-08-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackGraph',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('arrival', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=64)),
                ('type', models.CharField(default='follows', max_length=16)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='sim.attackgraph')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=16)),
                ('p_succ', models.JSONField(blank=True, default=dict)),
                ('p_detect', models.JSONField(blank=True, default=dict)),
                ('controls', models.JSONField(blank=True, default=list)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('ui', models.JSONField(blank=True, default=dict)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='sim.attackgraph')),
            ],
        ),
    ]
